[project]
name = "compliance-case-automatic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen>=0.9.9",
    "cpmpy>=0.9.26",
    "dotenv>=0.9.9",
    "openai>=1.40.0",
    "pandas>=2.3.2",
    "pip>=25.2",
    "pulp>=3.2.2",
    "pydantic>=2.11.7",
    "pysat>=3.2.2",
    "pysmt==0.9.0",
    "python-sat>=1.8.dev20",
    "setuptools>=80.9.0",
    "six>=1.17.0",
    "tiktoken>=0.11.0",
    "z3-solver>=4.15.3.0",
]
